### ISSUE TITLE
UnicodeEncodeError in collection names

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-library#1]
Copied from Transkribus/TranskribusWebUI#7 by @kansallisarkisto 

Steps to reproduce:

Create a collection with a name including e.g. "ö"
Actual behaviour:
As much as logging in with an account which should show the collection in question, i.e.
UnicodeEncodeError at /library/ingest_mets_url
'ascii' codec can't encode characters in position 8640-8642: ordinal not in range(128)

Expected behaviour:
A collection with the name given is created an usable.

**Comment by hackmanschorsch** [comment]
Seems to work?
