### ISSUE TITLE
Display of statistics

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-library#10]
Whether or not we make the individual stats better integrated to the data returned by TRPserver or the WebUI (#9) we should be try to display these in a less stringy way.

**Comment by cziaarm** [comment]
Will be dealt with by Transkribus/TranskribusServer#19

**Comment by hackmanschorsch** [comment]
rest services (Transkribus/TranskribusServer#19) at server are done
@maxbry the page status stats could be showed now as well

**Comment by cziaarm** [comment]
#17
