### ISSUE TITLE
Provide and show last accessed doc and page in the collection table

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-library#17]
for showing in collection table and to go directly to the edit page for this page.
needs rest service to get last saved page for a user, if no one found search for last accessed document and load first page
Will be provided via collection metadata

**Comment by hackmanschorsch** [comment]
Rest service example to get the latest 'save' action of the collection with ID 2305.
As 'userid' use the currently logged-in user in the WebUI. 'typeId' 1 means we are only interested in 'Save' actions. (Other actions would be 'Login', 'Access document', 'Change status'. But these are not actions where a user really has worked on the document. 'nValues=1' delivers the latest 'Save' for this user.
https://transkribus.eu/TrpServer/rest/actions/list?collId=2305&userid=206&typeId=1&nValues=1

For the latest action for a document we can use the docID (='id')
https://transkribus.eu/TrpServer/rest/actions/list?id=23218&userid=206&typeId=1&nValues=1

The returning object returns the colld, docId and pageNr. With these we can create the link to the edit page.

Or we could provide somewhere a list with just the last 5 save actions a user had made regardless of the collection or document with:
https://transkribus.eu/TrpServer/rest/actions/list?userid=206&typeId=1&nValues=5

@maxbry : So you could start to integrate the links to the edit interface with this service from the collection table (link to document and pageNr) and the document table (link to pageNr)

**Comment by hackmanschorsch** [comment]
And by the way: We could also use the 'time' of the returned action to show in a row 'Date of Change'. This way we allow the user to sort after recently changed collections / docs as wanted in #6 for last accessed.

**Comment by hackmanschorsch** [comment]
The links from the collection/documents table are still missing

**Comment by cziaarm** [comment]
typeId=1 will mean that we only see pages which we have saved, so jump to links can only appear for when a page has been saved by you for a document (or collection)

I've only got a few links appearing myself. Are you not seeing links when you should?

I guess that you should have one for collection 2305 as I can see from https://transkribus.eu/TrpServer/rest/actions/list?collId=2305&userid=206&typeId=1&nValues=1 that you have a save action

Please give me some examples and tell me the browser in case there is an issue with the way the jump to links are being appended.

Thanks

**Comment by hackmanschorsch** [comment]
Okay great- now I found it. 
At the moment I can see 5 identical 'Jump to's' to the same document and page?

**Comment by hackmanschorsch** [comment]
And may for testing you could omit the userid and should get the actions for arbitrary users.

**Comment by hackmanschorsch** [comment]
Just saw that in the documents table I see only one link for above document but in the collections table are 5.

**Comment by cziaarm** [comment]
Relabel: "Go to last saved page in this collection/document" as appropriate

**Comment by cziaarm** [comment]
When searching/filtering it will reload the the jump to link a number of times

**Comment by maxbry** [comment]
The title says showing `last_accessed`, but I'm only seeing `last_saved`. When accessing a page, the notification does not change for me. Also, the title says collection table, i.e. documents table, but the notifications are in the collection**s** table

**Comment by cziaarm** [comment]
last access only available for documents so last saved

Use "Return to the page that you last edited"
