### ISSUE TITLE
500 internal server error after logout and subsequent login

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TWI-library#18]
NB: not sure whether this is the right repo to file this issue against, please move if needed!

Login for user 1, logout, login user 2 --> 500 Server Error

Interestingly this only happens for one out of three user accounts I have (eva.lang@ieee.org).

URL: https://transkribus.eu/readTest/login/?next=/readTest/library/ 
OS: Windows 10
Browser: Firefox ESR 52.3.0 (32-Bit)

**Comment by cziaarm** [comment]
Hi Eva,

 I think I have replicated and fixed this in latest deployment (just now)

Please confirm

Rory

**Comment by EvaMLang** [comment]
The 500 is gone now.

I still get a 404 and therefore reopen issue #19 as login redirects me wrongly to https://transkribus.eu/library
