### ISSUE TITLE
Sorting/Searching datatables

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-library#20]
Copied from Transkribus/TWI-mc/#40
Sorting handles confuse me - intial setup now would allow for

    sorting by images (sorry, makes no sense for me)
    sorting by view (sorry, makes no sense either)
    sorting by stats (yay, this is what I would like to have)

![grafik](https://user-images.githubusercontent.com/17451573/30901776-72a4e404-a369-11e7-9297-a49844a91d30.png)

Would also expect

    sorting by "Document title and description" (behavior: sort by document name)

When I toggle one of the buttons, the sorting handles for sorting by view are gone, only sorting options 1/3 above remain
![grafik](https://user-images.githubusercontent.com/17451573/30901932-e38dba9c-a369-11e7-8d14-8af44fae3e2e.png)

Again: would expect sorting by name and stats, nothing else...

**Comment by hackmanschorsch** [comment]
And also searching in the document title/description/ID is necessary. Otherwise you can't find your collection or document if there are really lots of them.

**Comment by EvaMLang** [comment]
As also commented in https://github.com/Transkribus/TWI-mc/issues/40 still missing sorting (and searching) by "Stats"

Sorting and searching works on columns "Document Title and description" as well as "pp.". 
Tried and successfully tested:
- searching by doc title
- searching by doc ID
- searching by number of pages (presents also results where description or title matches - would consider as OK and not that often used (?))

@hackmanschorsch: do we keep this issue open until sorting/searching by stats is also handled? Please advise, thank you.

**Comment by hackmanschorsch** [comment]
I would prefer to close it for milestone mc-v0.03 and reopen it maybe later on. Stats are difficult to handle because they are expensive to select at the server/database side for all documents at once. At the moment we call it just for a single document.

But maybe we could allow to search for the Stats row again and then if a user shows all of it's documents on the first page and waits until all Stats are loaded then he should be able to search in those? What do you think @maxbry?

**Comment by cziaarm** [comment]
- [x] Make the ID (which is hidden in the image column) searchable

**Comment by EvaMLang** [comment]
Test succeeded for sorting / searching for
- TrpCol / TrpDoc ID
- TrpCol / TrpDoc description (any fragment, even those hidden behind the "more" link)
- No. of docs 
- Roles
