### ISSUE TITLE
Collection icons are not refreshed

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TWI-library#22]
When changing the default number of collections on the collection overview, details for the newly added collections are not refreshed, see screenshot below.

**Comment by EvaMLang** [comment]
![grafik](https://user-images.githubusercontent.com/17451573/31653245-2a79a11a-b322-11e7-99b9-2ec974bb26fb.png)

**Comment by EvaMLang** [comment]
Could have been a temporary issue, though - could not reproduce, so believe this was only temporarily. Any suggestions?

**Comment by maxbry** [comment]
Could not reproduce as well.

**Comment by EvaMLang** [comment]
I'm closing the issue now as it seems to have been a temporary thing. Will re-open in case it occurs again. Thank you @maxbry for testing
