### ISSUE TITLE
Datatables: Reload data when 'Show entries' number increases

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-library#23]
Loading of data (ajax) must be repeated when a user changes the number of entries he wants to see, e.g. change from 'Show 10' to 'Show 20' entries. It seems that it does not reload all but only some of the entries.

**Comment by cziaarm** [comment]
got it

**Comment by maxbry** [comment]
I had a look as well and didn't find the reason.  The ajax has been executed correctly, the values have been set to the cells but they didn't refresh in the view. I'm curious to see you commit..
