### ISSUE TITLE
Access to wrong document after search by ID

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TWI-library#25]
Windows 10, FF, www.transkribus.eu/readTest

Steps to reproduce:
1) access mycollections, search for specific collection by ID
![2017-11-10_search_step1](https://user-images.githubusercontent.com/17451573/32650218-3f91a3a2-c5fd-11e7-8165-30d92dec7b02.PNG)
2) click on search result --> wrong collection is opened
![2017-11-10_search_step2_wrong_direct](https://user-images.githubusercontent.com/17451573/32650221-410de574-c5fd-11e7-9549-c68606122139.PNG)

@cziaarm @hackmanschorsch please move to appropriate repo and assign responsible person for fixing. Thank you!

**Comment by hackmanschorsch** [comment]
Added max to this collection for testing
