### ISSUE TITLE
Re-write collections list and documents list view

### ISSUE THREAD

**Issue by bejohu** [Transkribus/TWI-library#30]
The goal here is to provide users with a basic but fast overview of their collections / documents. 

All of this refers to _refactor_ branch.

_views.py_

- [x] Use django's built-in pagination. Retrieve items from TrpServer API using _LazyJsonClient_ (https://github.com/Transkribus/TWI-library/issues/31).

Test data can be found in the wiki: https://read02.uibk.ac.at/wiki/index.php/Architecture:Tools:Webinterfaces:API:Examples

```python
from django.conf import settings
from django.core.paginator import Paginator

from . import forms
from .services import LazyJsonClient

@login_required
def collection_list(request):

  # retrieve TrpServer session id for this user
  ...

  client = LazyJsonClient('https://api.example.org', headers={'Accept': 'application/json', 'JSESSIONID': session_id})

  col_list = client.get_col_list()

  paginator = Paginator(contact_list, page_size)

  ...

  # ... see https://docs.djangoproject.com/en/1.11/topics/pagination/#using-paginator-in-a-view

  # decouple TrpServer response data type from names in template
  context = {'items': [{'name': item.col_name, 'id': item.id, ...} for item in col_list]}

  return render(request, template_name='/library/collection/list.html', context=context)
```

- [x] Use regular bootstrap table in template. Render information included in items of _col_list_ only (i.e. no ajax, etc.).

- [x] Apply bootstrap to _collections/list.html_ template for layout and appearance.

- [x] Do the same for _/library/documents_ endpoint.

- [x] Add _q_ parameter to documents list. If specified, use _findDocuments_ endpoint (see https://transkribus.eu/TrpServer/Swadl/wadl.html) to retrieve paginated list of matches.

- [x] Add search form (method="get") to _/library/documents/list.html_ template to make search available.

- [x] Make results in _collection_list_ and _document_list_ sortable by forwarding GET params to _LazyJsonClient_.

- [x] Add form (method="get") with select element for setting sort params to retrieve sorted list. Above ther should be a _<label>_ that says "Sort By:". The options should take the form:

 - Title: ascending
 - Title: descending

User feedback is required for providing input on what else to sort by.

- [x] Refactor collection_list and document_list [ListView](https://docs.djangoproject.com/en/1.11/ref/class-based-views/generic-display/#listview)

- [x] When page is loaded, avoid any elements from changing their height during rendering due to images being loaded. For example, by explicitly setting image dimensions _<img height="...." ...>_ or by setting a fixed height in the stylesheets:

```CSS
.image {
  width: auto;
  height: 120px;
}
```

**Comment by cziaarm** [comment]
Also mods to TWI-utils to make sessionId available for LazyJsonClient Transkribus/TWI-utils@f01a7ca

first steps == the second sentence in 1.
