### ISSUE TITLE
Auto-generate models.py based on SQL schema

### ISSUE THREAD

**Issue by bejohu** [Transkribus/TWI-library#37]
- [transkribus.py](https://github.com/Transkribus/TWI-library/blob/refactor/transkribus.py): generated by _inspectdb_ database models, gets updated regularly to reflect current DB structure

 - [models.py](https://github.com/Transkribus/TWI-library/blob/refactor/models.py): contains proxy models inheriting from models in _transkribus.py_, maybe have custom methods and attributes, and managers.

- [x] Create _transkribus.py_ using _inspectdb_ command as described [here](https://docs.djangoproject.com/en/1.11/howto/legacy-databases/#auto-generate-the-models). Note that database _views_ might not be included in the result.

**Comment by bejohu** [comment]
Ideally, _models.py_ can be updated when changes to the data base are made without losing any of the custom methods added to the model classes. One way of doing this might by using [proxy models](https://docs.djangoproject.com/en/1.11/topics/db/models/#proxy-models):

 - _database.py_: contains database models, gets updated regularly to reflect current DB structure

 - _models.py_: contains proxy models inheriting from models in _database.py_ with custom methods

**Comment by cziaarm** [comment]
e7963dadc3ca02fe09634dbeeb429d1218178bb1
