### ISSUE TITLE
Requirements for collection list item

### ISSUE THREAD

**Issue by bejohu** [Transkribus/TWI-library#39]
Details on information to presented and actions to be offered for each item in the list of collections (_collection_list_). Items are intended to present a summary of the most important pieces of information or actions. More detailed information on collection are shown in a separete _collection_detail_ view.

What information should each item in the list of collections include (e.g. collection name, number of documents in collection)? What actions should be available (e.g. click on link to document list)?  How should that things be presented (e.g. progress as a percentage)?

You may add your suggestions in the comments below. Please be specific and try to explain how and why your suggestion is important.

 - collection name (everyone)

 - progress:

   - for crowdsourcing collections only

   - pages with status FINAL of total pages as a percentage

 - link to collection details (everyone)

 - link to list of documents (everyone)

 - link to keyword search (administrator)

**Comment by bejohu** [comment]
Some suggestions have already been submitted:

Collection

 - Name (=title)
 - MyRole: owner, reader,…
 - Creation date
 - Type: public, private (currently all are private)
 - Description
 - No. of documents, pages linking to overview of documents processed
 - Status of pages linking to overview on status
 - No. of tags used in the collection with link to tag overview
 - No. of users linking to overview of users
 - HTR models for this collection linking to overview of HTR models
 - Jobs performed in this collection linking to job overview

**Comment by cziaarm** [comment]
I think we have roughly three types of view (view not necessarily in the django sense, but maybe) for the collection list. So below I'm just structuring the list(s) into these "views".

General users: basic descriptive info on the collections:

- Title
- Description
- Representative thumbnail
- No. of documents, pages linking to list of documents

Public transcribers (ie crowd sourcing): descriptive info + info on progress of transcription effort:

- Title
- Description
- Representative thumbnail
- No. of documents, pages linking to overview of documents processed
- Status of pages linking to overview on status
- No. of tags used in the collection with link to tag overview

Collection editors/owner/administrators (all info available):

- Title
- Description
- Representative thumbnail
- No. of documents, pages linking to overview of documents processed
- Status of pages linking to overview on status
- No. of tags used in the collection with link to tag overview
- MyRole: owner, reader,…
- Creation date
- Type: public, private (currently all are private)
- No. of users linking to overview of users
- HTR models for this collection linking to overview of HTR models
- Jobs performed in this collection linking to job overview
