### ISSUE TITLE
Show last access time in the document table

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-library#6]
Allows to sort with this column later on, value must be added to the rest service first

**Comment by hackmanschorsch** [comment]
Following service gives you the latest save of an arbitrary user of the required doc:
https://transkribus.eu/TrpServer/rest/actions/list?id={docId}&typeId=1&nValues=1

**Comment by cziaarm** [comment]
<del>#17</del>

**Comment by cziaarm** [comment]
Last *Accessed" date in it's own column.... but don't think we can sort on it (as it would be fetched by ajax call)

**Comment by hackmanschorsch** [comment]
Okay - probably we deliver the documents already sorted with 'last accessed' from the server as default. Instead of sorting after IDs.
